
import type { Metadata } from "next";
import { Geist, Geist_Mono, Permanent_Marker } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/Components/Theme-provider";
import { FloatingDockDemo } from "@/Components/FloatingDock";






const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const permanentMarker = Permanent_Marker({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-permanent-marker",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en"  suppressHydrationWarning>
      <head>
        <title>Radhika</title>
        <style>
             @import url('https://fonts.googleapis.com/css2?family=Pacifico&display=swap');
             @import url('https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400..900;1,400..900&display=swap');
        </style>
      
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} ${permanentMarker.variable} antialiased`}  
      >
      
           <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <div className="relative ">
           
        <main className=""> 
          {children}
        </main>
        <div className="fixed bottom-0 md:left-1/2 md:-translate-x-1/2">
        <FloatingDockDemo/>
       
        </div>
        </div> 
        </ThemeProvider>

      </body>
    </html>
  );
}
